# OpenStack modules

mod 'cinder',
  :git => 'https://git.openstack.org/openstack/puppet-cinder',
  :ref => 'stable/mitaka'

mod 'glance',
  :git => 'https://git.openstack.org/openstack/puppet-glance',
  :ref => 'stable/mitaka'

mod 'horizon',
  :git => 'https://git.openstack.org/openstack/puppet-horizon',
  :ref => 'stable/mitaka'

mod 'keystone',
  :git => 'https://git.openstack.org/openstack/puppet-keystone',
  :ref => 'stable/mitaka'

mod 'neutron',
  :git => 'https://git.openstack.org/openstack/puppet-neutron',
  :ref => 'stable/mitaka'

mod 'nova',
  :git => 'https://git.openstack.org/openstack/puppet-nova',
  :ref => 'stable/mitaka'

mod 'openstack_extras',
  :git => 'https://git.openstack.org/openstack/puppet-openstack_extras',
  :ref => 'stable/mitaka'

mod 'openstacklib',
  :git => 'https://git.openstack.org/openstack/puppet-openstacklib',
  :ref => 'stable/mitaka'

mod 'swift',
  :git => 'https://git.openstack.org/openstack/puppet-swift',
  :ref => 'stable/mitaka'

mod 'vswitch',
  :git => 'https://git.openstack.org/openstack/puppet-vswitch',
  :ref => '3.0.0'

# External modules

mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache',
  :branch => '1.8.x'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt',
  :branch => '2.2.x'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat',
  :branch => '1.2.x'

mod 'corosync',
  :git => 'https://github.com/puppet-community/puppet-corosync',
  :tag => '0.8.0'

mod 'dns',
  :git => 'https://github.com/theforeman/puppet-dns',
  :tag => '3.1.0'

mod 'firewall',
  :git => 'https://github.com/puppetlabs/puppetlabs-firewall',
  :branch => '1.7.x'

mod 'inifile',
  :git => 'https://github.com/puppetlabs/puppetlabs-inifile',
  :branch => '1.4.x'

mod 'memcached',
  :git => 'https://github.com/saz/puppet-memcached',
  :tag => 'v2.8.1'

mod 'mongodb',
  :git => 'https://github.com/puppetlabs/puppetlabs-mongodb',
  :branch => '0.12.0'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql',
  :branch => '3.6.x'

mod 'postgresql',
  :git => 'https://github.com/puppetlabs/puppetlabs-postgresql',
  :branch => '4.7.1'

mod 'powerdns',
  :git => 'https://github.com/antonlindstrom/puppet-powerdns',
  :tag => '0.0.5'

mod 'python',
  :git => 'https://github.com/stankevich/puppet-python',
  :tag => '1.10.0'

mod 'qpid',
  :git => 'https://github.com/dprince/puppet-qpid',
  :tag => '1.0.3'

mod 'rabbitmq',
  :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq',
  :tag => '5.6.0'

mod 'rsync',
  :git => 'https://github.com/puppetlabs/puppetlabs-rsync',
  :tag => '0.4.0'

mod 'staging',
  :git => 'https://github.com/nanliu/puppet-staging',
  :tag => '1.0.4'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :branch => '4.9.x'

mod 'sysctl',
  :git => 'https://github.com/duritong/puppet-sysctl',
  :tag => 'v0.0.11'

mod 'vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo',
  :branch => '1.3.x'

mod 'xinetd',
  :git => 'https://github.com/puppetlabs/puppetlabs-xinetd',
  :tag => '1.5.0'
